#!/bin/sh


gcc generate_instances.c -o generate_instances

gcc solve_backtracking.c -o solve_backtracking

gcc solve_backtracking_optimised.c -o solve_backtracking_optimised

gcc -Wall solve_dp.c -o solve_dp


./generate_instances 2 15 3 100 instances.txt


./solve_backtracking instances.txt results_backtracking.txt

./solve_backtracking_optimised instances.txt results_backtracking_optimised.txt

./solve_dp instances.txt results_dp.txt

python3 compare_algos_plot.py results_backtracking.txt results_backtracking_optimised.txt results_dp.txt

