#!/bin/sh


gcc generate_instances_dec.c -o generate_instances_dec

gcc solve_backtracking.c -o solve_backtracking

gcc solve_backtracking_optimised.c -o solve_backtracking_optimised


./generate_instances_dec 5 10 10 100 instances_dec.txt


./solve_backtracking instances_dec.txt results_backtracking_dec.txt

./solve_backtracking_optimised instances_dec.txt results_backtracking_optimised_dec.txt


python3 compare_algos_plot.py results_backtracking_dec.txt results_backtracking_optimised_dec.txt

