#!/bin/sh

case $# in
	[0-1])
		printf "%s \n" "Nombre d'arguments insuffisants"
		exit 1
		;;
	
	2)
		printf "Nombre d'arguments : $#\n"
		printf '%d\n' $(($1 + $2))
		;;
	
	3)
		printf "Nombre d'arguments : $#\n"
		case $3 in
			'+' | '-' | '*' | '/' | '%')
				printf '%d\n' $(($1 $3 $2))
				;;
		
			*)
				printf '%s %s \n' "$3" ": Opération non prise en charge"
				
		esac
		;;
		
	*)
		printf "%s \n" "Trop d'arguments : entrer 2 ou 3 arguments"
		;;

esac
