#!/bin/sh

i=0

case $# in
	[0-1])
		printf 'Usage: suffixer suffixe chaine... \n'
		exit 1
		;;
	
	*)
		:

esac

for num ; do
	case $i in
		0)
			i=$(($i + 1))
			;;
			
		*)	
			printf "$num$1 \n"

	esac
	
done
