#!/bin/sh



my_random=$(awk 'BEGIN { srand(); print int(rand()*1001) }')

printf "$my_random \n"

read choix


i=0


while [ "$choix" != "=" ]; do
	
	if [ "$choix" = ">" ]; then
       		my_random=$(awk 'BEGIN { srand(); print int(rand()*1001) }')
    	
    	fi
    	
    	if [ "$choix" = "<" ]; then
        	my_random=$(awk 'BEGIN { srand(); print int(rand()*1001) }')
   	fi

	i=$((i + 1))	
	
	printf "$my_random \n"
    	read choix

done


printf "nb_secret : Vous avez trouvé $my_random en $i coups \n"
